# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wardno', models.TextField(max_length=30)),
                ('bedno', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('btime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.TextField(max_length=30)),
                ('rno', models.TextField(max_length=10, unique=True)),
                ('contact_no', models.TextField(max_length=13)),
                ('addr', models.TextField(max_length=50)),
                ('sex', models.TextField(max_length=7)),
                ('age', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PatientTreatments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptr1', to='pbs.PatientDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trid', models.IntegerField()),
                ('trno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='pbs.PatientDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=30, unique=True)),
                ('tname', models.TextField(max_length=50)),
                ('tcost', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='patienttreatments',
            name='ptid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptr2', to='pbs.Treatment'),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='brno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billdetails', to='pbs.PatientDetails'),
        ),
    ]
